"""Legal files of a mod, generated from panzer-build-logic/legal.

Inputs: legal/catalog.toml (license texts, third-party components) and the
mod's merged [legal] table:

    [legal]                  # common TOML, or the mod's own complete table
    holder = "Panzer"
    code = "AGPL-3.0-only"   # SPDX ids from the catalog
    assets = "CC-BY-NC-SA-4.0"

    [legal.third_party]      # mod TOML
    components = ["zstd"]

Outputs: LICENSE (summary), the full text of each license used (LICENSE-AGPL,
LICENSE-CC, ...), NOTICE (third-party notices and their license texts) and the
README's license and footer blocks. The build packs LICENSE*, NOTICE into
META-INF/ of every jar and sources jar.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from panzer_mod import BUILD_LOGIC, Mod, PanzerError, read_toml

RULE = "=" * 70
THIN = "-" * 70
GENERATED = ("Generated by panzer-build-logic (legal/) from [legal] in the mod's TOML.\n"
             "Edit those and run `panzer sync`; do not edit this file by hand.")


def catalog(build_logic: Path = BUILD_LOGIC) -> dict:
    return read_toml(build_logic / "legal" / "catalog.toml")


class Legal:
    """The resolved legal setup of one mod."""

    def __init__(self, mod: Mod, build_logic: Path = BUILD_LOGIC):
        self.mod = mod
        self.dir = build_logic / "legal"
        self.catalog = catalog(build_logic)
        legal = mod.legal
        for key in ("holder", "code", "assets"):
            if not legal.get(key):
                raise PanzerError(f"{mod.name}: [legal] {key} is missing (common TOML or the mod's own [legal]).")
        self.holder = legal["holder"]
        self.code = self._license(legal["code"])
        self.assets = self._license(legal["assets"])
        names = legal.get("third_party", {}).get("components", [])
        unknown = [n for n in names if n not in self.catalog.get("components", {})]
        if unknown:
            raise PanzerError(f"{mod.name}: [legal.third_party] components {unknown} are not in legal/catalog.toml.")
        self.components = [dict(self.catalog["components"][n], id=n) for n in names]

    def _license(self, spdx: str) -> dict:
        entry = self.catalog.get("licenses", {}).get(spdx)
        if entry is None:
            known = ", ".join(self.catalog.get("licenses", {}))
            raise PanzerError(f"{self.mod.name}: license '{spdx}' is not in legal/catalog.toml (known: {known}).")
        return dict(entry, spdx=spdx)

    # ----------------------------------------------------------------- files

    def files(self) -> dict[str, str | None]:
        """Path -> content for every legal file; None means the file must not exist."""
        out: dict[str, str | None] = {"LICENSE": self.summary()}
        used = {self.code["file"], self.assets["file"]}
        for lic in (self.code, self.assets):
            out[lic["file"]] = (self.dir / lic["text"]).read_text(encoding="utf-8")
        for entry in self.catalog.get("licenses", {}).values():
            if entry["file"] not in used:
                out[entry["file"]] = None
        out["NOTICE"] = self.notice() if self.components else None
        return out

    def summary(self) -> str:
        name = self.mod.name
        wrap = lambda s: textwrap.fill(s, 67, initial_indent="   ", subsequent_indent="   ")
        parts = [RULE, f"{name.upper()} LICENSING", RULE, "", f"Copyright (c) {self.holder}", "",
                 f"{name} is made of two kinds of content, each under its own license.", "",
                 "1. SOURCE CODE",
                 wrap(f"All source code in this repository (Java, C++, build scripts) is licensed "
                      f"under the {self.code['name']} ({self.code['spdx']})."),
                 f"   Full text: {self.code['file']}, or {self.code['url']}", "",
                 "2. ASSETS AND BRANDING",
                 wrap(f"All non-code content, including textures, models, artwork, icons, logos, "
                      f"documentation and branding, is licensed under the {self.assets['name']} "
                      f"({self.assets['spdx']})."),
                 f"   Full text: {self.assets['file']}, or {self.assets['url']}"]
        if self.components:
            parts += ["", "3. THIRD-PARTY COMPONENTS"]
            for c in self.components:
                parts.append(wrap(f"{c['name']} ({c['license']}): {c['bundled_as']}. {c['url']}"))
            parts.append("   Their copyright notices and license texts are in NOTICE.")
        parts += ["", THIN, GENERATED]
        return "\n".join(parts) + "\n"

    def notice(self) -> str:
        name = self.mod.name
        parts = [name, f"Copyright (c) {self.holder}", "",
                 textwrap.fill(f"{name} includes the third-party software below. Each keeps its own "
                               "copyright and license, reproduced here as their authors require.", 70)]
        for c in self.components:
            text = (self.dir / c["text"]).read_text(encoding="utf-8").rstrip()
            parts += ["", RULE, c["name"], c["url"], c["copyright"], f"License: {c['license']}",
                      f"Included as: {c['bundled_as']}", THIN, text]
        parts += ["", THIN, GENERATED]
        return "\n".join(parts) + "\n"

    # ----------------------------------------------------------------- README

    def readme_blocks(self) -> dict[str, str]:
        code, assets = self.code, self.assets
        rows = [
            "| Content | License |",
            "|---|---|",
            f"| Source code | [{code['label']}]({code['url']}), see [`{code['file']}`](./{code['file']}) |",
            f"| Artwork, branding and documentation | [{assets['label']}]({assets['url']}), "
            f"see [`{assets['file']}`](./{assets['file']}) |",
        ]
        for c in self.components:
            rows.append(f"| {c['name']} (bundled) | [{c['license']}]({c['url']}), see [`NOTICE`](./NOTICE) |")
        lines = ["## License", "", *rows, ""]
        for title, lic in (("Source code", code), ("Artwork", assets)):
            if lic.get("summary"):
                lines += [f"**{title}:** {lic['summary'].format(holder=self.holder)}", ""]
        lines.append("See [`LICENSE`](./LICENSE) for the full summary.")
        footer = f"Code: **{code['label']}** · Art: **{assets['label']}** · Made by **{self.holder}**"
        return {"license": "\n".join(lines), "footer": footer}
